In [54]:
import os
from xgraph.definitions import ROOT_DIR
from pathlib import Path
# from openpyxl import Workbook, load_workbook
from IPython.display import display
import pandas as pd
import sys
import time
import sqlite3
import numpy as np

In [159]:
df = pd.read_excel(Path(ROOT_DIR, 'quantitative_results', 'GCN_GIN_PL.xlsx'), sheet_name='GCN', index_col=[0, 1], header=[0, 1])

In [111]:
# df = df['GCN'].unstack(0)
df = df.unstack().unstack(0).unstack(0)

In [160]:
# df.index = df.index.append(pd.Index([(np.array(sp * 0.1).round(1), 'abc') for sp in range(5, 10)]))
# Add one index into the multi index
df = pd.concat([df, pd.DataFrame(index=pd.MultiIndex.from_tuples([(np.array(sp * 0.1).round(1), 'abc') for sp in range(5, 10)]))]).sort_index()

In [182]:
# df.sort_index(inplace=True)
pd.concat([df, pd.DataFrame(index=pd.MultiIndex.from_product([[0.5, 0.6, 0.7, 0.8, 0.9], ['new_method']]), columns=pd.MultiIndex.from_tuples([('ff', metric) for metric in ['Fidelity+', 'Fidelity-']]))]).sort_index().sort_index(axis=1)

                   ba_infe                        ba_lrp           ba_shapes  \
                  Accuracy Fidelity+ Fidelity- Fidelity+ Fidelity- Fidelity+
0.5 DeepLIFT        0.6025    0.9265   -0.0209    0.5174    0.1642    0.4610
    FlowMask           NaN       NaN       NaN    0.3416    0.5113    0.4140
    FlowShap_orig   0.9274    0.9546   -0.0314    0.5164    0.2229    0.4134
    FlowShap_plus   0.9070    0.9493   -0.0243    0.5164    0.2709    0.4136
    GNNExplainer    0.8144    0.8473   -0.0158    0.5109    0.4802    0.4125
...                    ...       ...       ...       ...       ...       ...
0.9 PGExplainer     0.2199    0.1979    0.4710    0.2076    0.5108    0.2515
    PGMExplainer    0.3612    0.5285    0.2081    0.0884    0.5110    0.2669
    SubgraphX          NaN       NaN       NaN       NaN       NaN       NaN
    abc                NaN       NaN       NaN       NaN       NaN       NaN
    new_method         NaN       NaN       NaN       NaN       NaN       NaN

                                 bace                bbbp  ...        cc  \
                  Fidelity- Fidelity+ Fidelity- Fidelity+  ... Fidelity+
0.5 DeepLIFT         0.3556    0.4679   -0.0794    0.5214  ...      None
    FlowMask         0.2695    0.3246   -0.0053    0.5776  ...      None
    FlowShap_orig    0.2256    0.5477   -0.1106    0.6111  ...      None
    FlowShap_plus    0.2271    0.5201   -0.0613    0.6481  ...      None
    GNNExplainer     0.2972    0.2969   -0.0576    0.4934  ...      None
...                     ...       ...       ...       ...  ...       ...
0.9 PGExplainer      0.4126    0.0348    0.1963    0.0457  ...      None
    PGMExplainer     0.4143    0.1663    0.1717    0.1557  ...      None
    SubgraphX           NaN    0.2771    0.0214       NaN  ...      None
    abc                 NaN       NaN       NaN       NaN  ...      None
    new_method          NaN       NaN       NaN       NaN  ...      None

                    clintox                  ff                  gg  \
                  Fidelity+ Fidelity- Fidelity+ Fidelity- Fidelity+
0.5 DeepLIFT         0.3752    0.0378       NaN       NaN      None
    FlowMask         0.3925    0.0697       NaN       NaN      None
    FlowShap_orig    0.3848   -0.0022       NaN       NaN      None
    FlowShap_plus    0.4015    0.0246       NaN       NaN      None
    GNNExplainer     0.3230    0.1686       NaN       NaN      None
...                     ...       ...       ...       ...       ...
0.9 PGExplainer      0.0559    0.2671       NaN       NaN      None
    PGMExplainer     0.1323    0.2250       NaN       NaN      None
    SubgraphX           NaN       NaN       NaN       NaN      None
    abc                 NaN       NaN       NaN       NaN      None
    new_method          NaN       NaN       NaN       NaN      None

                  graph_sst2               tox21
                   Fidelity+ Fidelity- Fidelity+ Fidelity-
0.5 DeepLIFT          0.3833    0.0352    0.1650   -0.0584
    FlowMask          0.3310    0.0687    0.1836   -0.0516
    FlowShap_orig     0.4196    0.0296    0.2059   -0.0642
    FlowShap_plus     0.4542    0.0337    0.2289   -0.0575
    GNNExplainer      0.2784    0.0904    0.1166   -0.0306
...                      ...       ...       ...       ...
0.9 PGExplainer       0.0208    0.4778    0.0208    0.0117
    PGMExplainer      0.0686    0.3654    0.0655    0.0021
    SubgraphX            NaN       NaN       NaN       NaN
    abc                  NaN       NaN       NaN       NaN
    new_method           NaN       NaN       NaN       NaN

[66 rows x 21 columns]

In [178]:
pd.DataFrame(index=pd.MultiIndex.from_product([[0.5, 0.6, 0.7, 0.8, 0.9], ['new_method']]), columns=pd.MultiIndex.from_tuples([('ff', metric) for metric in ['Fidelity+', 'Fidelity-']]))

                      ff
               Fidelity+ Fidelity-
0.5 new_method       NaN       NaN
0.6 new_method       NaN       NaN
0.7 new_method       NaN       NaN
0.8 new_method       NaN       NaN
0.9 new_method       NaN       NaN

In [10]:
with sqlite3.connect(Path(ROOT_DIR, 'quantitative_results', 'GCN_GIN_PL.db')) as conn:
    df['GCN'].to_sql('GCN_PL', conn, if_exists='replace')
    df['GIN'].to_sql('GIN_PL', conn, if_exists='replace')

In [22]:
with sqlite3.connect(Path(ROOT_DIR, 'quantitative_results', 'GCN_GIN_PL.db')) as conn:
    df_sql = pd.read_sql('select * from GCN_PL', conn, index_col=['model', 'sparsity'])
    display(df_sql)

,,"('ba_shapes', 'Fidelity+')","('ba_shapes', 'Fidelity-')","('ba_lrp', 'Fidelity+')","('ba_lrp', 'Fidelity-')","('clintox', 'Fidelity+')","('clintox', 'Fidelity-')","('tox21', 'Fidelity+')","('tox21', 'Fidelity-')","('bbbp', 'Fidelity+')","('bbbp', 'Fidelity-')","('bace', 'Fidelity+')","('bace', 'Fidelity-')","('graph_sst2', 'Fidelity+')","('graph_sst2', 'Fidelity-')","('ba_infe', 'Fidelity+')","('ba_infe', 'Fidelity-')","('ba_infe', 'Accuracy')"
model,sparsity,,,,,,,,,,,,,,,,,
GradCAM,0.5,0.4502,0.4015,0.5163,0.0886,0.3096,0.0035,0.1135,-0.0580,0.4350,0.0058,0.3516,0.0527,0.2875,0.0464,0.9213,-0.0304,0.9025
DeepLIFT,0.5,0.4610,0.3556,0.5174,0.1642,0.3752,0.0378,0.1650,-0.0584,0.5214,-0.0231,0.4679,-0.0794,0.3833,0.0352,0.9265,-0.0209,0.6025
GNNExplainer,0.5,0.4125,0.2972,0.5109,0.4802,0.3230,0.1686,0.1166,-0.0306,0.4934,0.0129,0.2969,-0.0576,0.2784,0.0904,0.8473,-0.0158,0.8144
PGExplainer,0.5,0.4162,0.4241,0.5113,0.5084,0.3093,0.3170,0.0281,0.0222,0.2353,0.2426,0.1749,0.1488,0.1289,0.1620,0.4282,0.4008,0.7057
GNN_GI,0.5,0.4143,0.3148,0.5151,0.3075,0.3634,0.0527,0.1741,-0.0519,0.5189,0.0424,0.2906,0.1080,0.4792,0.0384,0.9526,-0.0305,0.8511
GNN_LRP,0.5,0.4143,0.2812,0.5191,0.1255,0.3781,0.0026,0.1546,-0.0641,0.4696,0.0083,0.3044,0.1047,0.3682,0.0765,0.9495,-0.0315,0.9826
FlowShap_orig,0.5,0.4134,0.2256,0.5164,0.2229,0.3848,-0.0022,0.2059,-0.0642,0.6111,-0.0501,0.5477,-0.1106,0.4196,0.0296,0.9546,-0.0314,0.9274
FlowShap_plus,0.5,0.4136,0.2271,0.5164,0.2709,0.4015,0.0246,0.2289,-0.0575,0.6481,-0.0174,0.5201,-0.0613,0.4542,0.0337,0.9493,-0.0243,0.9070
FlowMask,0.5,0.4140,0.2695,0.3416,0.5113,0.3925,0.0697,0.1836,-0.0516,0.5776,0.0467,0.3246,-0.0053,0.3310,0.0687,NaN,NaN,NaN
PGMExplainer,0.5,0.4118,0.3903,0.5042,0.4896,0.3073,0.0625,0.0752,-0.0315,0.3332,0.1263,0.1828,0.0669,0.2382,0.0617,0.5942,0.0932,0.8408
SubgraphX,0.5,NaN,NaN,0.5654,-0.0159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GradCAM,0.6,0.4530,0.4076,0.5175,0.2738,0.2849,0.0273,0.1204,-0.0477,0.3954,0.0757,0.3325,0.0730,0.2372,0.1264,0.9233,-0.0277,0.8578
DeepLIFT,0.6,0.4535,0.3969,0.5052,0.4076,0.3682,0.0680,0.1661,-0.0475,0.4430,0.0344,0.4802,-0.0648,0.2855,0.0718,0.9286,-0.0164,0.5814
GNNExplainer,0.6,0.4125,0.3939,0.5109,0.5060,0.3087,0.2342,0.1109,-0.0050,0.4330,0.1499,0.3066,0.0101,0.2240,0.1646,0.8700,0.0052,0.7499
PGExplainer,0.6,0.4178,0.4189,0.5113,0.5108,0.2927,0.3344,0.0246,0.0222,0.1893,0.3359,0.1349,0.1800,0.0909,0.2656,0.3999,0.4181,0.6433
GNN_GI,0.6,0.4142,0.3704,0.5185,0.4988,0.3624,0.1087,0.1824,-0.0314,0.4824,0.1192,0.2906,0.1294,0.4107,0.0959,0.9572,-0.0292,0.8440
GNN_LRP,0.6,0.4136,0.3469,0.5193,0.3587,0.3813,0.0331,0.1631,-0.0509,0.4219,0.0717,0.2941,0.1221,0.2730,0.1400,0.9501,-0.0305,0.9666
FlowShap_orig,0.6,0.4134,0.3474,0.5173,0.4202,0.3699,0.0187,0.2214,-0.0501,0.5794,0.0117,0.5438,-0.1083,0.3333,0.0757,0.9574,-0.0302,0.9196
FlowShap_plus,0.6,0.4133,0.3405,0.5174,0.4545,0.4139,0.0880,0.2594,-0.0365,0.6418,0.0587,0.5338,-0.0321,0.4194,0.0892,0.9527,-0.0195,0.8916
FlowMask,0.6,0.4142,0.3858,0.1999,0.5113,0.4071,0.1262,0.2053,-0.0387,0.5379,0.1209,0.3545,0.0401,0.2948,0.1257,NaN,NaN,NaN
PGMExplainer,0.6,0.4116,0.4055,0.4862,0.5086,0.2917,0.0893,0.0821,-0.0262,0.2963,0.1768,0.1599,0.0669,0.1887,0.0909,0.6351,0.0964,0.7873
SubgraphX,0.6,NaN,NaN,0.5653,-0.0063,NaN,NaN,0.0541,-0.0425,0.3594,-0.0710,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GradCAM,0.7,0.4483,0.4117,0.5127,0.4812,0.2494,0.0601,0.1130,-0.0342,0.3257,0.1811,0.3049,0.0938,0.1710,0.1465,0.8928,-0.0222,0.7852
DeepLIFT,0.7,0.4338,0.4105,0.4949,0.5059,0.3483,0.1103,0.1547,-0.0366,0.3824,0.1375,0.4689,-0.0306,0.2127,0.0840,0.9294,-0.0057,0.5576
GNNExplainer,0.7,0.4189,0.4120,0.5102,0.5107,0.2618,0.2820,0.1157,-0.0179,0.3466,0.3134,0.2889,0.1000,0.1851,0.2603,0.8214,0.0758,0.6296
PGExplainer,0.7,0.4225,0.4161,0.5110,0.5109,0.2217,0.3239,0.0188,0.0158,0.1460,0.4059,0.1127,0.1789,0.0474,0.3357,0.3420,0.4054,0.5300
GNN_GI,0.7,0.4105,0.3935,0.5109,0.5096,0.3478,0.1740,0.1754,-0.0122,0.4488,0.2282,0.2965,0.1564,0.3437,0.1161,0.9597,-0.0257,0.8113
GNN_LRP,0.7,0.4059,0.3849,0.5193,0.4973,0.3527,0.0776,0.1526,-0.0383,0.3748,0.1518,0.2748,0.1344,0.2237,0.1642,0.9502,-0.0286,0.9311
FlowShap_orig,0.7,0.4131,0.3762,0.5179,0.5049,0.3491,0.0616,0.2261,-0.0343,0.5271,0.1177,0.5336,-0.0963,0.2628,0.0952,0.9590,-0.0270,0.8924
FlowShap_plus,0.7,0.4119,0.3781,0.5174,0.5097,0.4279,0.1676,0.2623,-0.0088,0.6222,0.1933,0.5456,0.0342,0.3725,0.1353,0.9524,-0.0086,0.8382
FlowMask,0.7,0.4143,0.4023,0.1283,0.5113,0.4002,0.1906,0.2040,-0.0254,0.4379,0.2307,0.3710,0.0840,0.2446,0.1626,NaN,NaN,NaN
PGMExplainer,0.7,0.4125,0.4014,0.4097,0.5108,0.2672,0.1226,0.0849,-0.0179,0.2495,0.2575,0.1654,0.0668,0.1689,0.0998,0.6059,0.1222,0.6996
SubgraphX,0.7,NaN,NaN,0.5582,0.0901,0.1345,-0.0444,0.0479,-0.0355,0.3171,-0.0289,0.3729,-0.0656,0.0408,-0.0020,NaN,NaN,NaN
GradCAM,0.8,0.3815,0.4090,0.5042,0.5099,0.1828,0.1098,0.0915,-0.0150,0.2152,0.3194,0.2641,0.1142,0.1224,0.2346,0.8389,0.0094,0.6338
DeepLIFT,0.8,0.4232,0.4141,0.3998,0.5107,0.2886,0.1654,0.1229,-0.0221,0.2936,0.2926,0.4075,0.0043,0.1491,0.1948,0.9372,0.0242,0.5112
GNNExplainer,0.8,0.4246,0.4120,0.4793,0.5108,0.1827,0.2887,0.0710,0.0223,0.2382,0.4225,0.2248,0.1647,0.1046,0.3993,0.7325,0.1474,0.4570
PGExplainer,0.8,0.4062,0.4129,0.4185,0.5108,0.1352,0.2931,0.0148,0.0115,0.0944,0.4461,0.0648,0.1826,0.0422,0.4089,0.2214,0.4581,0.3589
GNN_GI,0.8,0.4123,0.4215,0.4417,0.5103,0.2898,0.2340,0.1635,-0.0028,0.4021,0.3407,0.2950,0.1887,0.2150,0.2105,0.9638,-0.0014,0.7577
GNN_LRP,0.8,0.4151,0.3999,0.5173,0.5094,0.2951,0.1387,0.1239,-0.0242,0.3068,0.2748,0.2399,0.1581,0.1398,0.2677,0.9566,-0.0208,0.8050
FlowShap_orig,0.8,0.4116,0.4043,0.5186,0.5099,0.2951,0.1261,0.1944,-0.0145,0.4399,0.2606,0.4951,-0.0584,0.1811,0.2192,0.9572,-0.0157,0.8064
FlowShap_plus,0.8,0.4111,0.3966,0.5195,0.5102,0.4120,0.2471,0.2296,0.0237,0.5583,0.3436,0.5210,0.1219,0.2537,0.3084,0.9493,0.0153,0.7532
FlowMask,0.8,0.4131,0.4236,0.1040,0.5111,0.3343,0.2388,0.1624,-0.0066,0.2691,0.3642,0.3418,0.1235,0.1647,0.2858,NaN,NaN,NaN
PGMExplainer,0.8,0.3980,0.4091,0.2721,0.5109,0.2286,0.1747,0.0771,-0.0083,0.2159,0.3468,0.1511,0.1019,0.1284,0.2034,0.5566,0.1470,0.5619
SubgraphX,0.8,NaN,NaN,0.5449,0.4895,0.1190,-0.0338,NaN,NaN,0.2493,-0.0005,0.3177,-0.0159,0.0298,0.0140,NaN,NaN,NaN
GradCAM,0.9,0.2079,0.4138,0.4335,0.5105,0.1076,0.1925,0.0561,0.0064,0.1175,0.4335,0.1783,0.1689,0.0699,0.3891,0.5051,0.2282,0.3781
DeepLIFT,0.9,0.3436,0.4144,0.1843,0.5109,0.1608,0.2210,0.0774,-0.0055,0.1858,0.4273,0.2769,0.0882,0.0739,0.3597,0.8243,0.1373,0.3640
GNNExplainer,0.9,0.3914,0.4120,0.2256,0.5108,0.0711,0.2627,0.0385,0.0197,0.0973,0.4783,0.0847,0.2050,0.0387,0.4650,0.4803,0.2912,0.2528
PGExplainer,0.9,0.2515,0.4126,0.2076,0.5108,0.0559,0.2671,0.0208,0.0117,0.0457,0.4815,0.0348,0.1963,0.0208,0.4778,0.1979,0.4710,0.2199
GNN_GI,0.9,0.3635,0.4168,0.2450,0.5104,0.1718,0.2594,0.1106,0.0128,0.2840,0.4430,0.2531,0.2163,0.0960,0.3403,0.9365,0.0708,0.5480
GNN_LRP,0.9,0.4057,0.4125,0.5009,0.5103,0.1733,0.2133,0.0811,-0.0070,0.1945,0.4049,0.1575,0.1823,0.0624,0.3984,0.9400,0.0383,0.5383
FlowShap_orig,0.9,0.4171,0.4128,0.5064,0.5103,0.1867,0.2058,0.1188,0.0033,0.3071,0.4153,0.3894,0.0409,0.0951,0.3638,0.9387,0.0729,0.5584
FlowShap_plus,0.9,0.4492,0.4127,0.5019,0.5104,0.2665,0.2610,0.1414,0.0394,0.3582,0.4796,0.4529,0.1902,0.1087,0.4691,0.9420,0.2531,0.5266
FlowMask,0.9,0.3443,0.4132,0.0549,0.5109,0.1845,0.2557,0.0757,0.0094,0.1368,0.4688,0.2014,0.1667,0.0747,0.4300,NaN,NaN,NaN
PGMExplainer,0.9,0.2669,0.4143,0.0884,0.5110,0.1323,0.2250,0.0655,0.0021,0.1557,0.4459,0.1663,0.1717,0.0686,0.3654,0.5285,0.2081,0.3612
SubgraphX,0.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2771,0.0214,NaN,NaN,NaN,NaN,NaN

                                        ('ba                        \
                       shapes', 'Fidelity+') shapes', 'Fidelity-')
model         sparsity
GradCAM       0.5                     0.4502                0.4015
DeepLIFT      0.5                     0.4610                0.3556
GNNExplainer  0.5                     0.4125                0.2972
PGExplainer   0.5                     0.4162                0.4241
GNN_GI        0.5                     0.4143                0.3148
GNN_LRP       0.5                     0.4143                0.2812
FlowShap_orig 0.5                     0.4134                0.2256
FlowShap_plus 0.5                     0.4136                0.2271
FlowMask      0.5                     0.4140                0.2695
PGMExplainer  0.5                     0.4118                0.3903
SubgraphX     0.5                        NaN                   NaN
GradCAM       0.6                     0.4530                0.4076
DeepLIFT      0.6                     0.4535                0.3969
GNNExplainer  0.6                     0.4125                0.3939
PGExplainer   0.6                     0.4178                0.4189
GNN_GI        0.6                     0.4142                0.3704
GNN_LRP       0.6                     0.4136                0.3469
FlowShap_orig 0.6                     0.4134                0.3474
FlowShap_plus 0.6                     0.4133                0.3405
FlowMask      0.6                     0.4142                0.3858
PGMExplainer  0.6                     0.4116                0.4055
SubgraphX     0.6                        NaN                   NaN
GradCAM       0.7                     0.4483                0.4117
DeepLIFT      0.7                     0.4338                0.4105
GNNExplainer  0.7                     0.4189                0.4120
PGExplainer   0.7                     0.4225                0.4161
GNN_GI        0.7                     0.4105                0.3935
GNN_LRP       0.7                     0.4059                0.3849
FlowShap_orig 0.7                     0.4131                0.3762
FlowShap_plus 0.7                     0.4119                0.3781
FlowMask      0.7                     0.4143                0.4023
PGMExplainer  0.7                     0.4125                0.4014
SubgraphX     0.7                        NaN                   NaN
GradCAM       0.8                     0.3815                0.4090
DeepLIFT      0.8                     0.4232                0.4141
GNNExplainer  0.8                     0.4246                0.4120
PGExplainer   0.8                     0.4062                0.4129
GNN_GI        0.8                     0.4123                0.4215
GNN_LRP       0.8                     0.4151                0.3999
FlowShap_orig 0.8                     0.4116                0.4043
FlowShap_plus 0.8                     0.4111                0.3966
FlowMask      0.8                     0.4131                0.4236
PGMExplainer  0.8                     0.3980                0.4091
SubgraphX     0.8                        NaN                   NaN
GradCAM       0.9                     0.2079                0.4138
DeepLIFT      0.9                     0.3436                0.4144
GNNExplainer  0.9                     0.3914                0.4120
PGExplainer   0.9                     0.2515                0.4126
GNN_GI        0.9                     0.3635                0.4168
GNN_LRP       0.9                     0.4057                0.4125
FlowShap_orig 0.9                     0.4171                0.4128
FlowShap_plus 0.9                     0.4492                0.4127
FlowMask      0.9                     0.3443                0.4132
PGMExplainer  0.9                     0.2669                0.4143
SubgraphX     0.9                        NaN                   NaN

                                                              \
                       lrp', 'Fidelity+') lrp', 'Fidelity-')
model         sparsity
GradCAM       0.5                  0.5163             0.0886
DeepLIFT      0.5                  0.5174             0.1642
GNNExplainer  0.5                  0.5109             0.4802
PGExplainer   0.5                  0.5113             0.5084
GNN_GI        0.5                  0.5151             0.3075
GNN_LRP       0.5                  0.5191             0.1255
FlowShap_orig 0.5                  0.5164             0.2229
FlowShap_plus 0.5                  0.5164             0.2709
FlowMask      0.5                  0.3416             0.5113
PGMExplainer  0.5                  0.5042             0.4896
SubgraphX     0.5                  0.5654            -0.0159
GradCAM       0.6                  0.5175             0.2738
DeepLIFT      0.6                  0.5052             0.4076
GNNExplainer  0.6                  0.5109             0.5060
PGExplainer   0.6                  0.5113             0.5108
GNN_GI        0.6                  0.5185             0.4988
GNN_LRP       0.6                  0.5193             0.3587
FlowShap_orig 0.6                  0.5173             0.4202
FlowShap_plus 0.6                  0.5174             0.4545
FlowMask      0.6                  0.1999             0.5113
PGMExplainer  0.6                  0.4862             0.5086
SubgraphX     0.6                  0.5653            -0.0063
GradCAM       0.7                  0.5127             0.4812
DeepLIFT      0.7                  0.4949             0.5059
GNNExplainer  0.7                  0.5102             0.5107
PGExplainer   0.7                  0.5110             0.5109
GNN_GI        0.7                  0.5109             0.5096
GNN_LRP       0.7                  0.5193             0.4973
FlowShap_orig 0.7                  0.5179             0.5049
FlowShap_plus 0.7                  0.5174             0.5097
FlowMask      0.7                  0.1283             0.5113
PGMExplainer  0.7                  0.4097             0.5108
SubgraphX     0.7                  0.5582             0.0901
GradCAM       0.8                  0.5042             0.5099
DeepLIFT      0.8                  0.3998             0.5107
GNNExplainer  0.8                  0.4793             0.5108
PGExplainer   0.8                  0.4185             0.5108
GNN_GI        0.8                  0.4417             0.5103
GNN_LRP       0.8                  0.5173             0.5094
FlowShap_orig 0.8                  0.5186             0.5099
FlowShap_plus 0.8                  0.5195             0.5102
FlowMask      0.8                  0.1040             0.5111
PGMExplainer  0.8                  0.2721             0.5109
SubgraphX     0.8                  0.5449             0.4895
GradCAM       0.9                  0.4335             0.5105
DeepLIFT      0.9                  0.1843             0.5109
GNNExplainer  0.9                  0.2256             0.5108
PGExplainer   0.9                  0.2076             0.5108
GNN_GI        0.9                  0.2450             0.5104
GNN_LRP       0.9                  0.5009             0.5103
FlowShap_orig 0.9                  0.5064             0.5103
FlowShap_plus 0.9                  0.5019             0.5104
FlowMask      0.9                  0.0549             0.5109
PGMExplainer  0.9                  0.0884             0.5110
SubgraphX     0.9                     NaN                NaN

                       ('clintox', 'Fidelity+') ('clintox', 'Fidelity-')  \
                                            NaN                      NaN
model         sparsity
GradCAM       0.5                        0.3096                   0.0035
DeepLIFT      0.5                        0.3752                   0.0378
GNNExplainer  0.5                        0.3230                   0.1686
PGExplainer   0.5                        0.3093                   0.3170
GNN_GI        0.5                        0.3634                   0.0527
GNN_LRP       0.5                        0.3781                   0.0026
FlowShap_orig 0.5                        0.3848                  -0.0022
FlowShap_plus 0.5                        0.4015                   0.0246
FlowMask      0.5                        0.3925                   0.0697
PGMExplainer  0.5                        0.3073                   0.0625
SubgraphX     0.5                           NaN                      NaN
GradCAM       0.6                        0.2849                   0.0273
DeepLIFT      0.6                        0.3682                   0.0680
GNNExplainer  0.6                        0.3087                   0.2342
PGExplainer   0.6                        0.2927                   0.3344
GNN_GI        0.6                        0.3624                   0.1087
GNN_LRP       0.6                        0.3813                   0.0331
FlowShap_orig 0.6                        0.3699                   0.0187
FlowShap_plus 0.6                        0.4139                   0.0880
FlowMask      0.6                        0.4071                   0.1262
PGMExplainer  0.6                        0.2917                   0.0893
SubgraphX     0.6                           NaN                      NaN
GradCAM       0.7                        0.2494                   0.0601
DeepLIFT      0.7                        0.3483                   0.1103
GNNExplainer  0.7                        0.2618                   0.2820
PGExplainer   0.7                        0.2217                   0.3239
GNN_GI        0.7                        0.3478                   0.1740
GNN_LRP       0.7                        0.3527                   0.0776
FlowShap_orig 0.7                        0.3491                   0.0616
FlowShap_plus 0.7                        0.4279                   0.1676
FlowMask      0.7                        0.4002                   0.1906
PGMExplainer  0.7                        0.2672                   0.1226
SubgraphX     0.7                        0.1345                  -0.0444
GradCAM       0.8                        0.1828                   0.1098
DeepLIFT      0.8                        0.2886                   0.1654
GNNExplainer  0.8                        0.1827                   0.2887
PGExplainer   0.8                        0.1352                   0.2931
GNN_GI        0.8                        0.2898                   0.2340
GNN_LRP       0.8                        0.2951                   0.1387
FlowShap_orig 0.8                        0.2951                   0.1261
FlowShap_plus 0.8                        0.4120                   0.2471
FlowMask      0.8                        0.3343                   0.2388
PGMExplainer  0.8                        0.2286                   0.1747
SubgraphX     0.8                        0.1190                  -0.0338
GradCAM       0.9                        0.1076                   0.1925
DeepLIFT      0.9                        0.1608                   0.2210
GNNExplainer  0.9                        0.0711                   0.2627
PGExplainer   0.9                        0.0559                   0.2671
GNN_GI        0.9                        0.1718                   0.2594
GNN_LRP       0.9                        0.1733                   0.2133
FlowShap_orig 0.9                        0.1867                   0.2058
FlowShap_plus 0.9                        0.2665                   0.2610
FlowMask      0.9                        0.1845                   0.2557
PGMExplainer  0.9                        0.1323                   0.2250
SubgraphX     0.9                           NaN                      NaN

                       ('tox21', 'Fidelity+') ('tox21', 'Fidelity-')  \
                                          NaN                    NaN
model         sparsity
GradCAM       0.5                      0.1135                -0.0580
DeepLIFT      0.5                      0.1650                -0.0584
GNNExplainer  0.5                      0.1166                -0.0306
PGExplainer   0.5                      0.0281                 0.0222
GNN_GI        0.5                      0.1741                -0.0519
GNN_LRP       0.5                      0.1546                -0.0641
FlowShap_orig 0.5                      0.2059                -0.0642
FlowShap_plus 0.5                      0.2289                -0.0575
FlowMask      0.5                      0.1836                -0.0516
PGMExplainer  0.5                      0.0752                -0.0315
SubgraphX     0.5                         NaN                    NaN
GradCAM       0.6                      0.1204                -0.0477
DeepLIFT      0.6                      0.1661                -0.0475
GNNExplainer  0.6                      0.1109                -0.0050
PGExplainer   0.6                      0.0246                 0.0222
GNN_GI        0.6                      0.1824                -0.0314
GNN_LRP       0.6                      0.1631                -0.0509
FlowShap_orig 0.6                      0.2214                -0.0501
FlowShap_plus 0.6                      0.2594                -0.0365
FlowMask      0.6                      0.2053                -0.0387
PGMExplainer  0.6                      0.0821                -0.0262
SubgraphX     0.6                      0.0541                -0.0425
GradCAM       0.7                      0.1130                -0.0342
DeepLIFT      0.7                      0.1547                -0.0366
GNNExplainer  0.7                      0.1157                -0.0179
PGExplainer   0.7                      0.0188                 0.0158
GNN_GI        0.7                      0.1754                -0.0122
GNN_LRP       0.7                      0.1526                -0.0383
FlowShap_orig 0.7                      0.2261                -0.0343
FlowShap_plus 0.7                      0.2623                -0.0088
FlowMask      0.7                      0.2040                -0.0254
PGMExplainer  0.7                      0.0849                -0.0179
SubgraphX     0.7                      0.0479                -0.0355
GradCAM       0.8                      0.0915                -0.0150
DeepLIFT      0.8                      0.1229                -0.0221
GNNExplainer  0.8                      0.0710                 0.0223
PGExplainer   0.8                      0.0148                 0.0115
GNN_GI        0.8                      0.1635                -0.0028
GNN_LRP       0.8                      0.1239                -0.0242
FlowShap_orig 0.8                      0.1944                -0.0145
FlowShap_plus 0.8                      0.2296                 0.0237
FlowMask      0.8                      0.1624                -0.0066
PGMExplainer  0.8                      0.0771                -0.0083
SubgraphX     0.8                         NaN                    NaN
GradCAM       0.9                      0.0561                 0.0064
DeepLIFT      0.9                      0.0774                -0.0055
GNNExplainer  0.9                      0.0385                 0.0197
PGExplainer   0.9                      0.0208                 0.0117
GNN_GI        0.9                      0.1106                 0.0128
GNN_LRP       0.9                      0.0811                -0.0070
FlowShap_orig 0.9                      0.1188                 0.0033
FlowShap_plus 0.9                      0.1414                 0.0394
FlowMask      0.9                      0.0757                 0.0094
PGMExplainer  0.9                      0.0655                 0.0021
SubgraphX     0.9                         NaN                    NaN

                       ('bbbp', 'Fidelity+') ('bbbp', 'Fidelity-')  \
                                         NaN                   NaN
model         sparsity
GradCAM       0.5                     0.4350                0.0058
DeepLIFT      0.5                     0.5214               -0.0231
GNNExplainer  0.5                     0.4934                0.0129
PGExplainer   0.5                     0.2353                0.2426
GNN_GI        0.5                     0.5189                0.0424
GNN_LRP       0.5                     0.4696                0.0083
FlowShap_orig 0.5                     0.6111               -0.0501
FlowShap_plus 0.5                     0.6481               -0.0174
FlowMask      0.5                     0.5776                0.0467
PGMExplainer  0.5                     0.3332                0.1263
SubgraphX     0.5                        NaN                   NaN
GradCAM       0.6                     0.3954                0.0757
DeepLIFT      0.6                     0.4430                0.0344
GNNExplainer  0.6                     0.4330                0.1499
PGExplainer   0.6                     0.1893                0.3359
GNN_GI        0.6                     0.4824                0.1192
GNN_LRP       0.6                     0.4219                0.0717
FlowShap_orig 0.6                     0.5794                0.0117
FlowShap_plus 0.6                     0.6418                0.0587
FlowMask      0.6                     0.5379                0.1209
PGMExplainer  0.6                     0.2963                0.1768
SubgraphX     0.6                     0.3594               -0.0710
GradCAM       0.7                     0.3257                0.1811
DeepLIFT      0.7                     0.3824                0.1375
GNNExplainer  0.7                     0.3466                0.3134
PGExplainer   0.7                     0.1460                0.4059
GNN_GI        0.7                     0.4488                0.2282
GNN_LRP       0.7                     0.3748                0.1518
FlowShap_orig 0.7                     0.5271                0.1177
FlowShap_plus 0.7                     0.6222                0.1933
FlowMask      0.7                     0.4379                0.2307
PGMExplainer  0.7                     0.2495                0.2575
SubgraphX     0.7                     0.3171               -0.0289
GradCAM       0.8                     0.2152                0.3194
DeepLIFT      0.8                     0.2936                0.2926
GNNExplainer  0.8                     0.2382                0.4225
PGExplainer   0.8                     0.0944                0.4461
GNN_GI        0.8                     0.4021                0.3407
GNN_LRP       0.8                     0.3068                0.2748
FlowShap_orig 0.8                     0.4399                0.2606
FlowShap_plus 0.8                     0.5583                0.3436
FlowMask      0.8                     0.2691                0.3642
PGMExplainer  0.8                     0.2159                0.3468
SubgraphX     0.8                     0.2493               -0.0005
GradCAM       0.9                     0.1175                0.4335
DeepLIFT      0.9                     0.1858                0.4273
GNNExplainer  0.9                     0.0973                0.4783
PGExplainer   0.9                     0.0457                0.4815
GNN_GI        0.9                     0.2840                0.4430
GNN_LRP       0.9                     0.1945                0.4049
FlowShap_orig 0.9                     0.3071                0.4153
FlowShap_plus 0.9                     0.3582                0.4796
FlowMask      0.9                     0.1368                0.4688
PGMExplainer  0.9                     0.1557                0.4459
SubgraphX     0.9                        NaN                   NaN

                       ('bace', 'Fidelity+') ('bace', 'Fidelity-')  \
                                         NaN                   NaN
model         sparsity
GradCAM       0.5                     0.3516                0.0527
DeepLIFT      0.5                     0.4679               -0.0794
GNNExplainer  0.5                     0.2969               -0.0576
PGExplainer   0.5                     0.1749                0.1488
GNN_GI        0.5                     0.2906                0.1080
GNN_LRP       0.5                     0.3044                0.1047
FlowShap_orig 0.5                     0.5477               -0.1106

In [ ]:

args_group = [f'-m benchmark.kernel.pipeline --task {task} --model_name {model_dataset[0]} --dataset_name {model_dataset[1]} ' \
              f'--target_idx {model_dataset[2]} --explainer {explainer} --sparsity {sparsity} ' \
              f'--log_file {task}_{model_dataset[1]}_{model_dataset[0]}_{explainer}_{sparsity}.log' \
              # f' --save_fig --nolabel'
              for model_series in ['GCN', 'GIN']
                  for sparsity in ['0.5', '0.6', '0.7', '0.8', '0.9']
                      for model_dataset in [(f'{model_series}_3l', 'clintox', 0), (f'{model_series}_3l', 'ba_lrp', 0),
                                            (f'{model_series}_3l', 'bbbp', 0), (f'{model_series}_3l', 'tox21', 2),
                                            (f'{model_series}_3l', 'bace', 0)]#(f'{model_series}_3l', 'clintox', 0), (f'{model_series}_3l', 'ba_lrp', 0),
                                            #  (f'{model_series}_3l', 'tox21', 2),  # (f'{model_series}_3l', 'ba_infe', 0),
                                            # (f'{model_series}_3l', 'bbbp', 0), (f'{model_series}_3l', 'bace', 0),
                                            # (f'{model_series}_3l', 'graph_sst2', 0)] (f'{model_series}_2l', 'ba_shapes', 0)
                          for explainer in ['Gem'] # ['GradCAM', 'PGMExplainer', 'DeepLIFT', 'GNNExplainer', 'PGExplainer', 'GNN_GI', 'GNN_LRP', 'FlowShap_orig', 'FlowShap_plus', ]

]